export {
  fetchmovies,
  genremovies,
  trendingpersonsuc,
  trendingpersonreq,
  trendingperson,
  topratedmoviereq,
  topratedmoviesuccess,
  toprated,
  watchlist,
  watchlistsuccess,
  watchlistreq,
  popularmovies,
  popularmoviesreq,
  popularmoviessuccess,
  nowplayingmovies,
  nowplayingreq,
  nowplayingsuccess,
} from "./Action";
